### ISSUE TITLE
Joseph Mathew

### ISSUE THREAD

**Issue by jma1999** [VIP-SMUR/24Fa-EnergyInBuildings-Com#1]

**Comment by kastnerp** [comment]
@jma1999 We need notebooks here asap!

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 04

### Overview:

- **Week Span:** `[09-09-2024]` to `[09-15-2024]`

### Tasks for This Week:

- [ ] **Task-1:** To understand the process of UBEM.
- [ ] **Task-2:** To look at different methods by which UBEM is executed and how different building parameters are inputted.

### Tasks:

##### Task: [To understand different existing methods of BEM as well as UBEM] -  _(completed)_

- **Description:** There are many existing ways in which building energy modeling is done, as well as, different methods by which building geometry and related data are processed to run a thermal simulation. I wanted to see how we can leverage these existing methods to help our use case. Also, to understand where we stand with respect to achieving our particular thermal simulation objectives.

- **Link to Work:** [[Link](https://docs.google.com/presentation/d/1JNc6lz630-T52qAKNN2nWqR39b52dmzBbukfHky4EV4/edit#slide=id.g3077c1a0d6b_0_30)] (Slides 7, 8, 9)

- **Outcome & Reflection:** We found two methods - shoebox & autozone - both seem viable.
 
### Challenges & Solutions:
- The challenge was in figuring out how the randomly generated data that would represent different building parameters could be used to generate accurate energy usage data.
- Solution is to run those data into a Grasshopper based thermal simulation to get the usage outputs.
 
### General Takeaway, Skills & Knowledge Acquired:
- Doing a literature review in an efficient way is a new skill acquired.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around getting energy usage data from the existing randomly generated building data (and the data obtained from various studies).
- **Peer Feedback:** There were some things that required clarification regarding how the method used for running a single building's thermal simulation can now be scaled to an urban scale - as well as in identifying which parameters were to be given more importance - which will be the next set of tasks.

### Personal Reflection:
- BEM is a very interesting process. The process just got more interesting now that we have an ML-model which needs to be trained with data that it can understand - which is very different from data that a Rhino/Grasshopper environment outputs - like surfaces and geometry.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/6a4343f4-a457-43ed-a712-9c0608a6aac9) 
![image](https://github.com/user-attachments/assets/8d0855c0-4669-4994-99d2-6679eb9c9319)

### Plans for Next Week:
- We now know how to get thermal usage data for one building and want to figure out how we can scale this process for multiple buildings at an urban scale
- We also realised that out of the randomly generated data, some parameters may stay constant for commercial buildings, some may now affect it at all, and some may affect it a lot - so we need to find out what parameters are to be chosen with what level of importance assigned to them.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 05

### Overview:

- **Week Span:** `[09-16-2024]` to `[09-22-2024]`

### Tasks for This Week:

- [ ] **Task-1:** To look at how our thermal simulation method for one building can be scaled for mutliple buildings.
- [ ] **Task-2:** To find parameters that apply specifically to commercial buildings in terms of energy consumption.

### Tasks:

##### Task: [Methods of UBEM & parameters for commercial buildings] -  _(completed)_

- **Description:** Looked at 2 models of UBEM - one by MIT - called UMI, and the other by Berkeley - called CityBES. For the parameters - identified what inputs were given into these models. 

- **Link to Work:** [[[Link](https://docs.google.com/presentation/d/1JNc6lz630-T52qAKNN2nWqR39b52dmzBbukfHky4EV4/edit#slide=id.g3077c1a0d6b_0_30)](https://docs.google.com/presentation/d/1JNc6lz630-T52qAKNN2nWqR39b52dmzBbukfHky4EV4/edit#slide=id.g3077c1a0d6b_0_443)] (Slides 23 & 24)

- **Outcome & Reflection:** Both UMI and CityBES achieve our objective - but we need to now figure out how to add additional parameters that can make our model unique.
 
### Challenges & Solutions:
- The challenge was to run thermal simulation for multiple buildings in a fast way.
- Solution is to either use the tools found - like UMI / CityBES - or to find a dataset which contains the required data.
 
### General Takeaway, Skills & Knowledge Acquired:
- Used UMI - it requires Rhino 8.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around running thermal simulation for multiple buildings.
- **Peer Feedback:** During our discussions, we decided to move ahead with the ComStock data parameters for the majority part as it included heating and cooling energy consumption data, but decided to add in some parameters from our end that would be unique to our model (need to identify those).

### Personal Reflection:
- We had discussions regarding using shading and footprint as unique parameters for our model - this would be an interesting process as we will need to figure out how this can be inputted into the model.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/28c49b50-fc7c-41f1-937d-c4e1bca7dfa7)
![image](https://github.com/user-attachments/assets/54621074-b22a-4430-9c6e-84b16039bf1b)

### Plans for Next Week:
- We were doing literature reviews and looking into existing tools for the most part so far - now it is time to dive into this and actually run our own simulations with the data that we have, for the city we are looking at for the moment. This will give us further issues to tackle - and a deeper understanding of the pipeline we will need to build.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 06

### Overview:

- **Week Span:** `[09-23-2024]` to `[09-29-2024]`

### Tasks for This Week:

- [ ] **Task-1:** Rebuild an urban-scale model for energy simulation (Tech Square as a case).

### Tasks:

##### Task: [Test energy model for Tech Square as example] -  _(completed)_

- **Description:** We wanted to see whether the parameters we've collected so far and methods we talked about could be applied to run an actual thermal simulation. This included modeling massing geometry for a section of Tech Square, choosing a building to run thermal simulation, identifying parameters that could be input into the ClimateStudio template that was used to run the simulation, and extracting contextual geometry that would be used for shading (as shading is one of the parameters we want to use as a unique feature to our model.) 

- **Link to Work:** [https://docs.google.com/presentation/d/1JNc6lz630-T52qAKNN2nWqR39b52dmzBbukfHky4EV4/edit#slide=id.g3077c1a0d6b_0_651] (Slides 29 to 35)

- **Outcome & Reflection:** It is clear that simulation for individual buildings are not an issue. However, this process can be made quicker by extracting geometry data from the datasets we are referring to. Furthermore, we can now look into ways of encoding footprint & contextual shading data into a format that the ML-model can understand.
 
### Challenges & Solutions:
- The challenge was to run thermal simulation using the building data we are currently using, furthermore, to look at a portion of Atlanta in particular for this case.
- ClimateStudio works fine for the time-being - but as we move up in adding more parameters, and running more buildings, I suspect we will not be able to use existing templates for much longer.
 
### General Takeaway, Skills & Knowledge Acquired:
- ClimateStudio - using the existing template to run thermal simulation using building data we currently have.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around running an energy model for a building in Tech Square so that we can start zoning in to new issues and workflows.
- **Peer Feedback:** We want to be able to extract geometry directly from the datasets we are referring to so that we won't have to model multiple buildings individually.

### Personal Reflection:
- Now we will be looking into making pipelines that solve specific problems in our overall workflow - the current workflow to target is extracting geometry data from IDF/OSM files.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/79fde057-76b6-452f-b3d3-3be3d04a7f40)
![image](https://github.com/user-attachments/assets/d64e4ec5-5a03-4275-b44c-941a2b088818)

### Plans for Next Week:
- To build a pipeline for extracting geometry data from IDF/OSM files that the dataset we are referring to gives us.
- To also figure out ways to encode information like shading and footprint into a way that can be inputed into the ML-model - this will also make our tool unique compared to existing tools.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 07

### Overview:

- **Week Span:** `[09-30-2024]` to `[10-06-2024]`

### Tasks for This Week:

- [ ] **Task-1:** Extract geometry information from IDF/OSM file and merge them to existing energy demand dataset.
- [ ] **Task-2:** Develop algorithm to recognize and classify footprint shape & contextual shading. _(ongoing)_
- [ ] **Task-3:** Study about how to encode such non-numeric variable to regression model. _(ongoing)_

### Tasks:

##### Task: [Extract geometry information from IDF/OSM file and merge them to existing energy demand dataset] -  _(completed)_

- **Description:** In order to extract geometry data from IDF files - the process was straightforward - get the IDF file, then convert it into the correct version that Ladybug can read, then it just needs to be plugged in and the required geometry data can be extracted. However, for OSM files, the process was a little trickier - the OSM file isn't read directly by Ladybug (it is able to read IDF and gbXML formats without issues) - so we opened our OSM file in OpenStudio - then exported it into an IDF and tried running it in GH but it was giving weird version errors. So we tried exporting it in the other format - gbXML - this time it gave a clearer error regarding a thermal resistance value for a component which seemed to be below it's threshold - so the solution was a straight-forward fix - you can either edit it directly by opening the xml file in notepad / you can edit the value in OpenStudio - we tried both - both worked! 

- **Link to Work:** [https://docs.google.com/presentation/d/1YwYqGYVsC_ukeOOAJawuhVWrvwQyaXqNCMKWhPEq4w8/edit#slide=id.g3064c5bb2b6_0_27] (Slides 17 to 23)

- **Outcome & Reflection:** It is clear that simulation for individual buildings are not an issue. However, this process can be made quicker by extracting geometry data from the datasets we are referring to. Furthermore, we can now look into ways of encoding footprint & contextual shading data into a format that the ML-model can understand.
 
### Challenges & Solutions:
- The challenge was to run thermal simulation using the building data we are currently using, furthermore, to look at a portion of Atlanta in particular for this case.
- ClimateStudio works fine for the time-being - but as we move up in adding more parameters, and running more buildings, I suspect we will not be able to use existing templates for much longer.
 
### General Takeaway, Skills & Knowledge Acquired:
- ClimateStudio - using the existing template to run thermal simulation using building data we currently have.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around running an energy model for a building in Tech Square so that we can start zoning in to new issues and workflows.
- **Peer Feedback:** We want to be able to extract geometry directly from the datasets we are referring to so that we won't have to model multiple buildings individually.

### Personal Reflection:
- Now we will be looking into making pipelines that solve specific problems in our overall workflow - the current workflow to target is extracting geometry data from IDF/OSM files.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/79fde057-76b6-452f-b3d3-3be3d04a7f40)
![image](https://github.com/user-attachments/assets/d64e4ec5-5a03-4275-b44c-941a2b088818)

### Plans for Next Week:
- To build a pipeline for extracting geometry data from IDF/OSM files that the dataset we are referring to gives us.
- To also figure out ways to encode information like shading and footprint into a way that can be inputed into the ML-model - this will also make our tool unique compared to existing tools.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 08

### Overview:

- **Week Span:** `[10-07-2024]` to `[10-13-2024]`

### Tasks for This Week:

- [x] **Task-1:** Finalize on building geometry parameters for model.
- [ ] **Task-2:** Planning for game to be presented at the Georgia Undergraduate Research Conference

### Tasks:

##### Task: [Finalizing features for energy simulation game] -  _(completed)_

- **Description:** This week was focussed on directing the research and model developed thus far so that they can be presented at the GURC Conference. For this purpose, we spent the week identifying the features that will be presented to the user for customization of the building geometry. 

- **Link to Work:** [https://docs.google.com/presentation/d/1YwYqGYVsC_ukeOOAJawuhVWrvwQyaXqNCMKWhPEq4w8/edit#slide=id.g309b8336532_0_0](url) (Slides 31 to 32)

- **Outcome & Reflection:** The developments that were made over the semester till now are finally coming together as an interactive product. The energy simulation game is going to be a great example of utilizing the surrogate models we are developing in this VIP program for real-world applications.
 
### Challenges & Solutions:
- This week was spent in completing the tasks - no particular challenges came up.
 
### General Takeaway, Skills & Knowledge Acquired:
- Diving into front-end and a bit of back-end tool development concepts.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around how we are going to develop the game and what it is going to be like.
- **Peer Feedback:** The weeks goals were met, everyone is excited about turning this into a web-based application.

### Personal Reflection:
- Tool development is something I've always admired - happy to finally be with a team that is building one. Looking forward to picking up key technical skills along this process so that I can apply them over the course of the coming semesters.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/3c4c9faa-4b63-45e4-a591-766b22aa82cb)

### Plans for Next Week:
- Finalise and develop concept for the game.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 09

### Overview:

- **Week Span:** `[10-14-2024]` to `[10-20-2024]`

### Tasks for This Week:

- [x] **Task-1:** Finalise and develop concept for the game

### Tasks:

##### Task: [Energy simulation game - framework] -  _(completed)_

- **Description:** For the game, drafted out a framework for parameters that can be edited by the user, coordinated with Anubha and Jessica regarding how to get the input for different building features from the user, and how the input should be treated to calculate features that can be used by the model. 

- **Link to Work:** [https://docs.google.com/presentation/d/1YwYqGYVsC_ukeOOAJawuhVWrvwQyaXqNCMKWhPEq4w8/edit#slide=id.g30c42d4e6bc_0_3](url) (Slide 36)

- **Outcome & Reflection:** Figuring out the processes involved in taking an ML model code and turning it into a working tool that can be used by anybody. 
 
### Challenges & Solutions:
- It was interesting to figure out how to get inputs from users in a manner that made it easy for them to understand what to input, as well as extracting the information that our model is trained on from minimum number of inputs from them.
 
### General Takeaway, Skills & Knowledge Acquired:
- Started learning about web/tool development - hoping to get comfortable with it towards the end of this year.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around how we are going to develop the game and what it is going to be like.
- **Peer Feedback:** The weeks goals were met, everyone is excited about turning this into a web-based application.

### Personal Reflection:
- Been using this paper as reference for developing the game: [https://www.tandfonline.com/doi/full/10.1080/19401493.2011.619668](url)
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/18f19900-a532-4b5a-9ff3-f9de7c9d8f75)

### Plans for Next Week:
- Develop a mockup for the game.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 10

### Overview:

- **Week Span:** `[10-21-2024]` to `[10-27-2024]`

### Tasks for This Week:

- [x] **Task-1:** Mock-up for the game

### Tasks:

##### Task: [Mockup] -  _(completed)_

- **Description:** Made a draft of what the game might look like, how the UI should function, so that we could get a clearer picture of the path forward in developing the tool. 

- **Link to Work:** [https://purple-star-7565.animaapp.io](url)

- **Outcome & Reflection:** We have a mockup now of what the game would look like ideally, we can now plan what can be achieved in time for the conference. 
 
### Challenges & Solutions:
- The geometry previewer seems to be a feature that needs to be explored in further detail.
 
### General Takeaway, Skills & Knowledge Acquired:
- We need to find a balance between the every possible feature that can be incorporated into the game and the timeline to the conference, so we are finding that sweetspot this week.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around the final features to be added to the game, and the front-end and back-end items that are essential to the functioning of the game.
- **Peer Feedback:** The weeks goals were met, everyone is working hard.

### Personal Reflection:
- It is unclear at this point how well the model performs based on inputs from the user, this is something that needs to validated further.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/a6539dce-a661-4130-8037-eea76a57064b)

### Plans for Next Week:
- Develop base models for the geometry previewer.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 11

### Overview:

- **Week Span:** `[10-28-2024]` to `[11-03-2024]`

### Tasks for This Week:

- [x] **Task-1:** Make base blender models that can be incorporated into the geometry previewer.

### Tasks:

##### Task: [Geometry previewer] -  _(completed)_

- **Description:** Created models in Blender for different building typologies. 

- **Link to Work:** [https://surrogate-model-game.vercel.app](url) (The geometry previewer)

- **Outcome & Reflection:** Made default models for 10 different building shapes: 'Wide rectangle', 'L shape', 'Square', 'Narrow rectangle', 'Courtyard', 'H shape', 'E shape', 'T shape', 'U shape', 'Cross shape'. 
 
### Challenges & Solutions:
- Figuring out how to incorporate the geometry previewer and connect it with user inputs was a challenge. It was solved eventually.
 
### General Takeaway, Skills & Knowledge Acquired:
- learnt about how to incorporate 3d geometry viewers using three.js.

### Team Meetings:
- **Meeting Highlights:** The discussions revolved around how we are going to finish the game up and start on the conference presentation.
- **Peer Feedback:** The weeks goals were met, everyone is working towards the conference deliverables.

### Personal Reflection:
- The geometry previewer in the game was finalised as a result of multiple trial and error methods, we ended up using the blender models, but we weren't able to figure out how to add windows in time. This could be a future fix.
 
### Visual Documentation:
- none.

### Plans for Next Week:
- Finalize presentation for the conference.

**Comment by jma1999** [comment]
## Weekly Notebook Entry - Week 12

### Overview:

- **Week Span:** `[11-04-2024]` to `[11-10-2024]`

### Tasks for This Week:

- [x] **Task-1:** Finalise presentation to be delivered by Anubha, Jessica, and Jiayi at the Georgia Undergraduate Research Conference (GURC) on `[11-09-2024]` at Emory's Oxford college.

### Tasks:

##### Task: [Final presentation for conference] -  _(completed)_

- **Description:** Set overall presentation framework, made the template, organised information, contributed to speaker's notes. 

- **Link to Work:** [https://docs.google.com/presentation/d/1rtB-uOHhjatFn1dHQK38u0IiTQq-_35K/edit#slide=id.p1](url) (This was presented at GURC)

- **Outcome & Reflection:** It is pleasing and relieving to see the semester's work come together as a tool that can be shared with anyone. 
 
### Challenges & Solutions:
- We had to ensure that all the work we did was conveyed at the conference, and that the technical details of the game and model were conveyed in a simplified manner.
 
### General Takeaway, Skills & Knowledge Acquired:
- Learnt quite a lot of interesting things from other presenters at the conference - hoped to see more presentations that catered to my professional interests.

### Team Meetings:
- **Meeting Highlights:** Meetings were mostly runthroughs of the presentation with the team.
- **Peer Feedback:** Everyone enjoyed the conference. It was a fun experience and a good culmination to the semester's work.

### Personal Reflection:
- Now that we have a model developed to this extent, we can spend the coming semesters developing this further, validating results further, as well as finding new applications to this model.
 
### Visual Documentation:
![image](https://github.com/user-attachments/assets/3140922e-1af4-44ea-8d51-c4a6fe882633) (photo clicked by Han-Syun)

### Plans for Next Week:
- Take a break as well.
- Run simulations in ClimateStudio with the models used for the game (to validate results)
- Work towards final VIP presentation
