### ISSUE TITLE
Anubha Mahajan

### ISSUE THREAD

**Issue by amahajan68** [VIP-SMUR/24Fa-EnergyInBuildings-Com#3]
### Overview
- **Week Span:** `[Start Date]` to `[End Date]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
 
 
##### Task: [Task Name] -  _(completed)_
- **Description:**
- **Link to Work:** [Link](#)
- **Outcome & Reflection:**
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1: Description and strategy.
has context menu

**Comment by amahajan68** [comment]
## Weekly Notebook Entry — Week 5
 
### Overview
- **Week Span:** `9/16` to `9/22`
 
### Tasks for This Week
- [ ] Task 1: 
 
 
### Tasks
 
##### Task: [Task Name] -  _(completed)_
- **Description:**
- **Link to Work:** [Link](#)
- **Outcome & Reflection:**
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1:

**Comment by amahajan68** [comment]
## Weekly Notebook Entry — Week 6
 
### Overview
- **Week Span:** `9/23` to `9/29`
 
### Tasks for This Week
- [ ] Task 1: 
 
 
### Tasks
 
##### Task: [Task Name] -  _(completed)_
- **Description:**
- **Link to Work:** [Link](#)
- **Outcome & Reflection:**
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1:

**Comment by amahajan68** [comment]
## Weekly Notebook Entry — Week 7
 
### Overview
- **Week Span:** `9/30` to `10/6`
 
### Tasks for This Week
- [ ] Task 1: 
 
 
### Tasks
 
##### Task: [Task Name] -  _(completed)_
- **Description:**
- **Link to Work:** [Link](#)
- **Outcome & Reflection:**
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1:
