### ISSUE TITLE
Jessica Hernandez

### ISSUE THREAD

**Issue by jhernandez312** [VIP-SMUR/24Fa-EnergyInBuildings-Com#4]

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [02]
 
### Overview
- **Week Span:** `[9/16]` to `[9/22]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Figure out what the models need as inputs
 
 
### Tasks
 
##### Task: [Task 1] -  _(completed)_
- **Description:**
- **Link to Work:**
![Screenshot 2024-10-06 180440](https://github.com/user-attachments/assets/b5c1feae-b693-441f-a9ca-88b3d14549fa)

![Screenshot 2024-10-06 180538](https://github.com/user-attachments/assets/5d8d0c33-8084-47e6-9bd7-f4ec62dd4686)

- **Outcome & Reflection:**
- We might be able to recreate the inputs of the 
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1: Description and strategy.
has context menu

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [03]
 
### Overview
- **Week Span:** `[9/23]` to `[9/29]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Set up Google TensorFlow Smart Buildings Simulator

 
### Tasks
 
##### Task: [Task 1] -  _(completed)_
- **Description:**
- set up Google TensorFlow Smart Buildings Simulator


- **Link to Work:** 
- ![image](https://github.com/user-attachments/assets/2c3da9db-9137-4592-b9be-bcc95a60f2e8)
- **Outcome & Reflection:**
- Took longer than expected to set up because there were issues with the virtual machine. It was running incredibly slow and the fix was to disable Windows' Optional Features. Had to go to System32 folder -> OptionalFeatures.exe -> and disable "Windows Subsystem for Linux", "Windows Hypervisor Platform" and "Virtual Machine Platform". The one that actually made a difference was disabling Windows Subsystem for Linux, but I didn't want to try all combinations. I'm using the Oracle VirtualBox for the virtual machine instead of VMWare since Ubuntu was crashing after being installed in VMWare. Perhaps it works now that Windows Hypervisor Platform is off, but VirtualBox works fine. Another option was installing  Ubuntu on my laptop, but in theory that seemed like the long options.
- As for the Google Dataset & RL model, the model has a couple of stages. Given the floorplans & metadata of HVAC systems of a buildings, it's able to simulate heat/energy consumption in a physics-based way. You can then optimize it by giving it real info?
- 
##### Task: [Google Model] - _(ongoing)_
- **Current Status:**
- in progress
- **Expected Completion:**
 - next week
### Challenges & Solutions
- Understand google model through either running it or reading the paper (prob a mix of both)
 
### General Takeaway, Skills & Knowledge Acquired
- Ubuntu uses the command line interface for lots of things including program installation. For github tools, the common option is to clone entire github repositories. For python libraries or even VSCode, you can type a command (i.e. pip install __ or sudo apt install ____)
- Ubuntu's keyboard shortcuts are similar to Windows'. 
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
- Ubuntu is fun to use
- Google's model seems to be for a single building at a time (however, it can adapt to a lot of different commercial buildings)
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1: Description and strategy.
has context menu

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [04]
 
### Overview
- **Week Span:** `[9/30]` to `[10/6]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
 
 
### Tasks
 
##### Task: [Task Name] -  _(completed)_
- **Description:**
- **Link to Work:** [Link](#)
- **Outcome & Reflection:**
 
##### Task: [Task Name] - _(ongoing)_
- **Current Status:**
- **Expected Completion:**
 
### Challenges & Solutions
-
 
### General Takeaway, Skills & Knowledge Acquired
-
 
### Team Meetings
- **Meeting Highlights:**
- **Peer Feedback:**
 
### Personal Reflection
-
 
### Visual Documentation (optional)
 
 
### Additional Notes & Resources (optional)
 
- [Resource Name](URL) - Brief description.
 
---
 
### Plans for Next Week
- [ ] Next Week's Task 1: Description and strategy.
has context menu

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [05]
 
### Overview
- **Week Span:** `[10/07]` to `[10/13]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1:  Google Tensorflow-- what does it do?
- [ ] Task 2:  frontend/backend of game (this weekend) -> how much work will it take to deploy and run?
 
 
##### Task: [Task 1] - _(ongoing)_
- **Current Status:**
- in progress
- **Expected Completion:**
- Monday
 
### Challenges & Solutions
-challenges: model took a long time to set up because of the linux environment
 
### General Takeaway, Skills & Knowledge Acquired
- In a nutshell, the Google Tensorflow model takes in floorplans and HVAC metadata to model thermal diffusion (using a physics based model called finite differences approximations). If you would like to optimize for a specific building, you need hourly data.
- 

### Team Meetings
- **Meeting Highlights:**
- The challenge for this week is being able to take the data from the ComStock website. We thought we needed a web scraper, but Hang figured out how to obtain the data relatively quickly.
- 
 
### Personal Reflection
- There's tools for different scales-- the google Tensorflow model is good for one building. We are more focused on a city scale.
- The main challenge for the game is connecting the ML model to the frontend somehow
 
### Plans for Next Week
- [ ] Next Week's Task 1: Frontend/backend for game.

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [08]
 
### Overview
- **Week Span:** `[10/28]` to `[11/03]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1:  Google Tensorflow-- what does it do?
- [ ] Task 2:  frontend/backend of game (this weekend) -> how much work will it take to deploy and run?
 
 
##### Task: [Task 1] - _(ongoing)_
- **Current Status:**
- in progress
- **Expected Completion:**
- Monday
 
### Challenges & Solutions
-challenges: model took a long time to set up because of the linux environment
 
### General Takeaway, Skills & Knowledge Acquired
- In a nutshell, the Google Tensorflow model takes in floorplans and HVAC metadata to model thermal diffusion (using a physics based model called finite differences approximations). If you would like to optimize for a specific building, you need hourly data.
- 

### Team Meetings
- **Meeting Highlights:**
- The challenge for this week is being able to take the data from the ComStock website. We thought we needed a web scraper, but Hang figured out how to obtain the data relatively quickly.
- 
 
### Personal Reflection
- There's tools for different scales-- the google Tensorflow model is good for one building. We are more focused on a city scale.
- The main challenge for the game is connecting the ML model to the frontend somehow
 
### Plans for Next Week
- [ ] Next Week's Task 1: Frontend/backend for game.

**Comment by jhernandez312** [comment]
## Weekly Notebook Entry — Week [09]
 
### Overview
- **Week Span:** `[11/04]` to `[11/10]`
 
### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1:  GURC (Georgia Undergraduate Conference) is this Saturday at Emory's Oxford college (~1 hour away from GT).
 
 
##### Task: [Task 1] - _(ongoing)_
- **Current Status:**
- in progress
- **Expected Completion:**
- Monday
 
### Challenges & Solutions
-challenges: last couple of slides were changed to explain the tech stack of the app
 
### General Takeaway, Skills & Knowledge Acquired
- Demo showcased the major features of the game. 

### Team Meetings
- **Meeting Highlights:**
- Jiayi will present the introduction, Anubha second, and I present last. 
- Experiment- each person has a persona (investor, HVAC engineer, etc). Kiana will lead the experiments
 
### Personal Reflection
-We're thinking of having a demo in addition to videos for 2 different personas. However, there's quite a bit of overlap between the two and perhaps we should merge these.
 
### Plans for Next Week
- [ ] Next Week's Task 1: Merge the videos, clean up the slides, and add demo
