### ISSUE TITLE
Weekly Notebook Entry - Week 04

### ISSUE THREAD

**Issue by jma1999** [VIP-SMUR/24Fa-EnergyInBuildings-Com#5]
### Overview:
- **Week Span:** `[09/09]` to `[09/15]`
### Tasks for This Week:
- [ ] **Task-1:** Gain overall familiarity with the mission and vision of VIP-SMUR.
- [ ] **Task-2:** Understand objectives and research interests of the various sub-groups and decide which sub-group fits my personal research/career goals.
- [ ] **Task-3:** Find learning material to get familiar with programming, data analytics, and ML - in order to be technically useful to the team and the tool we're trying to build.
### Challenges & Solutions:
- Main challenge was in understanding the ML-model that was built so far beyond the surface level of understanding - this took some time, hardwork, and research - however, it is an improving ongoing process.
 
### General Takeaway, Skills & Knowledge Acquired:
- Enrolled in the edX course offered by NUS for Data Science - it is helping me to develop my data analytics and programming skillsets.
- Along with the aforementioned data analytics course - also taking a machine learning course which is helping me understand the different types of ML-models and how to interface with them - this is of particular use as it helps me think of how I can transfer different types of data from the architectural and building sciences components of our research to the ML-model in the right way.

### Team Meetings:
- **Meeting Highlights:** Got to know the team members, and got to understand the diverse backgrounds we are all from.
- **Peer Feedback:** Peers are all helpful, hardworking, and competent.

### Personal Reflection:
- Expanding my current skills and knowledge to data science and machine learning has a learning curve - but it feels very fulfilling to be able to gain relevant knowledge that fits into my overall goals as well as to be able to gain additional technical skills for contributing to the team.
 
### Visual Documentation:
 _None for this week._
 
### Additional Notes & Resources:
 _None for this week._
 
### Plans for Next Week:
- [ ] **Next Week's Task-1:** To understand the process of UBEM.
- [ ] **Next Week's Task-2:** To find parameters of commercial buildings that are most likely to affect their energy consumption.
- [ ] **Next Week's Task-3:** To look at different methods by which UBEM is executed and how different building parameters are inputted.
